version: "3"

services:
  hamster-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: hamster-web
    ports:
      - 127.0.0.1:${APP_PORT}:80
    env_file:
      - .env
